### Login

POST {{url}}/client/api/auth/login
Content-Type: application/json

{
  "account": "1234",
  "password": "1234"
}

> {%
    client.global.set("account", response.body.account);
    client.global.set("accessToken", response.body.accessToken);
%}

### 404

GET {{url}}/example/404
Authorization: Bearer {{accessToken}}

### 403

GET {{url}}/test